CREATE OR REPLACE TABLE `FINANCIAL_STATUS_DB`.`FINANCIAL_STATUS` (
  `cuit` VARCHAR(14) NOT NULL,
  `financial_status` TINYINT(1) NOT NULL,
  `dni` VARCHAR(8),
  `full_name` VARCHAR(50),
  PRIMARY KEY(`cuit`)
);